### ISSUE TITLE
Figure out licensing

### ISSUE THREAD

**Issue by davclark** [dlab-projects/equal-read-interface#3]
For now, the most sensible thing is probably Affero GPL, which is a "viral" license that forces folks to share even if only made available as a web service. Currently, we are using an ISC license (a very permissive license).

**Comment by davclark** [comment]
Standard license from OTL:

http://ipira.berkeley.edu/software-copyright-notice-and-disclaimer

**Comment by susangrand** [comment]
Susan needs to figure out how to talk to Taun about this.  What does she need to know?

**Comment by davclark** [comment]
At this point, I spoke to the campus office for intellectual property. The UC has certain guidelines on what's acceptable, and the preferred license is one that essentially gives anyone full access to use the code as they wish. Further modifications need not be shared. Thus, it is truly permissive for all parties.

Thus, we should develop only things that are free to share. Tuan should maintain her data as a proprietary asset, and we will not "mix" the data into the code that is attached to the license.

**Comment by davclark** [comment]
Committed BSD 2-clause!
