### ISSUE TITLE
Learn Django

### ISSUE THREAD

**Issue by davclark** [dlab-projects/equal-read-interface#4]
A good template is [here](https://github.com/imkevinxu/django-kevin).

This is a fork that came from an older version of the book [Two Scoops of Django](http://twoscoopspress.com/products/two-scoops-of-django-1-8).

cc: @tonyshenyy

**Comment by davclark** [comment]
If you want me to help, please use anaconda and try this:

```
$ conda create -n django python=3 ipython-notebook django
```

**Comment by yadelab** [comment]
I ran the command, with anaconda installed, I get this:

Python 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:03:53) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import django
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named 'django'

**Comment by davclark** [comment]
Ah - you are not running the 'django' environment. So, you can address this one of two ways:
1. Before running anything, you do `$ source activate django`.
2. Install django to the base environment: `$ conda install django`.

Sorry for the confusion!

**Comment by yadelab** [comment]
Nice, that works! But do I have to run 
   source activate django
Everytime, 
or should I add it as a PATH to my .bashrc?

**Comment by davclark** [comment]
You shouldn't add this in the PATH. The `source activate django` could go directly in your .bashrc (or .bash_profile / .profile). You should do this before an `export PATH` line (either before an existing line, or add that line).

**Comment by davclark** [comment]
I guess this is done?
