### ISSUE TITLE
Figure out how to access postgres

### ISSUE THREAD

**Issue by davclark** [dlab-projects/equal-read-interface#5]
You probably want to have an approach where you can access postgres (or alternatively sqlite) on your local machine, and also use a database on mercury.

You can ask me to set up a database on mercury for you, and I'll give you access to that database.

cc: @yadelab

**Comment by davclark** [comment]
The basic test will be to set up the Django tutorial to use postgres on your machine, and then be sure you can get that working on mercury. You should probably finish #4 first!

**Comment by tonyshenyy** [comment]
A little bit confused on installing Psycopg2 on Windows. What's the meaning of virtual environment? How to set it up? Link: http://www.stickpeople.com/projects/python/win-psycopg/

**Comment by tonyshenyy** [comment]
I finally figured it out, but I am gonna install and use anaconda to be consistent.
