### ISSUE TITLE
Use Anaconda w/ python 3.4

### ISSUE THREAD

**Issue by davclark** [dlab-projects/equal-read-interface#6]
Get an installer from here:

http://conda.pydata.org/miniconda.html

**Comment by davclark** [comment]
If you already have another python 3.4 version, follow instructions to get pip here:

https://packaging.python.org/en/latest/installing.html#requirements-for-installing-packages

**Comment by yadelab** [comment]
Hey Dav,

Could you please upload/make me a database in the server so I can play with
it. Also, what was the database you said I can download on my Linux machine?

Yadel

**Comment by davclark** [comment]
You might be referring to sqlite! I'll set up postgres next week.

**Comment by tonyshenyy** [comment]
I am going to close this issue since both Yadel and I have installed Django on our laptops successfully though I am still using Windows lol
