### ISSUE TITLE
Update setttings.py to point to a postgresql database

### ISSUE THREAD

**Issue by davclark** [dlab-projects/equal-read-interface#7]
Also write down the steps to set up the database (e.g., what to name it, how to set up permissions).

Let me know if you aren't able to do this. I thought you told me you already figured it out!

**Comment by davclark** [comment]
Postgres has better search indexing. We should switch to this before we start implementing search.

**Comment by susangrand** [comment]
Yiyang make an account on www.heroku.com
set up postgres on heroku

**Comment by davclark** [comment]
http://www.enterprisedb.com/resources-community/webcasts-podcasts-videos/videos/how-create-postgres-database-using-pgadmin

**Comment by tonyshenyy** [comment]
Why do I get the error saying that 'settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.', even though I already set the ENGINE value to be 'django.db.backends.postgresql_psycopg2'?

**Comment by davclark** [comment]
Excellent reporting! We'll look at this tomorrow.

**Comment by tonyshenyy** [comment]
I think I solved it. It's just a conflict between local setting and remote setting I think. But now, I have a question that why every time I run 'heroku local', I will get a Traceback without any further info?

**Comment by tonyshenyy** [comment]
The full message is:
forego | starting web.1 on port 5000
web.1 | Traceback (most recent call last):

That's it. I am not so sure why the port number is 5000. I am guessing there is some issue with the Procfle? Or could it be that I created the Django project first before installing and initializing herku? Well, the latter guess may be just my superstition.

**Comment by tonyshenyy** [comment]
Well, some more thoughts here. I tried to run 'heroku config' to dig something out, but it said 'no apps specified'. Then I tried 'heroku config --app equal_read' both inside and outside the project folder. No success with returning message '! Couldn't find that app'. Need some help definitely.

**Comment by tonyshenyy** [comment]
More findings... Ran 'heroku apps', got 'equal-read-interface'. Well, that's our repo name. How could I change it to 'equal_read' which is our real app?

**Comment by tonyshenyy** [comment]
It seems that gunicorn is not compatible with Windows. We shall discuss all the above issues tomorrow. See you all in the meeting.
