### ISSUE TITLE
Have a look at the dav-cleanup branch

### ISSUE THREAD

**Issue by davclark** [dlab-projects/equal-read-interface#8]
I could only assign one person, but @tonyshenyy you should both have a look. We now have a functional app, done in the way @tonyshenyy had initially set things up. Sorry my django is so rusty!

Ideally, @yadelab could start working on improving the templates, but my guess is more explanation will be needed. I think a default of a list view with a search bar makes a lot of sense.

**Comment by davclark** [comment]
@tonyshenyy should definitely be able to run the app. This is done by `equal_read/manage.py runserver`. It should basically just work. Write a comment below if you get stuck.

**Comment by susangrand** [comment]
Is this a comment?

**Comment by davclark** [comment]
@susangrand per your requests about content-free responses, I won't reply here.
