### ISSUE TITLE
Yadel to finish the mock up design by Monday,Oct 19th, 2015

### ISSUE THREAD

**Issue by yadelab** [dlab-projects/equal-read-interface#9]

**Comment by yadelab** [comment]
There are some styling issues that I need to fix for the new UI Design that I just completed. Yiyang please wait for my cue later today, before you begin integrating it with the Django template.

**Comment by yadelab** [comment]
@tonyshenyy  You now have the template you need to start working on the model. @davclark  and @tonyshenyy  please take a look at the design, give me any feedback you have.

**Comment by davclark** [comment]
Looks good @yadelab. Two issues: 
1. the image on the index is stretched
2. We should have margins around the content on the thumbnails view

Let's have a discussion about integrating this template in a new issue?
